// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message containing the user's name.
type HolaRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HolaRequest) Reset()         { *m = HolaRequest{} }
func (m *HolaRequest) String() string { return proto.CompactTextString(m) }
func (*HolaRequest) ProtoMessage()    {}
func (*HolaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *HolaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HolaRequest.Unmarshal(m, b)
}
func (m *HolaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HolaRequest.Marshal(b, m, deterministic)
}
func (m *HolaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HolaRequest.Merge(m, src)
}
func (m *HolaRequest) XXX_Size() int {
	return xxx_messageInfo_HolaRequest.Size(m)
}
func (m *HolaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HolaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HolaRequest proto.InternalMessageInfo

func (m *HolaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HolaReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HolaReply) Reset()         { *m = HolaReply{} }
func (m *HolaReply) String() string { return proto.CompactTextString(m) }
func (*HolaReply) ProtoMessage()    {}
func (*HolaReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *HolaReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HolaReply.Unmarshal(m, b)
}
func (m *HolaReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HolaReply.Marshal(b, m, deterministic)
}
func (m *HolaReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HolaReply.Merge(m, src)
}
func (m *HolaReply) XXX_Size() int {
	return xxx_messageInfo_HolaReply.Size(m)
}
func (m *HolaReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HolaReply.DiscardUnknown(m)
}

var xxx_messageInfo_HolaReply proto.InternalMessageInfo

func (m *HolaReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "protobuf.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "protobuf.HelloReply")
	proto.RegisterType((*HolaRequest)(nil), "protobuf.HolaRequest")
	proto.RegisterType((*HolaReply)(nil), "protobuf.HolaReply")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x86, 0x5d, 0x10, 0xdb, 0x9d, 0x7a, 0x90, 0xf8, 0x41, 0xe9, 0x49, 0x03, 0x4a, 0x4f, 0x23,
	0xd4, 0x83, 0xe0, 0xb1, 0x88, 0x14, 0x41, 0x28, 0xed, 0xcd, 0x5b, 0x76, 0x3b, 0xb6, 0x8b, 0xb3,
	0x4e, 0x4c, 0xfa, 0xe1, 0xfe, 0x7b, 0xd9, 0xb4, 0xa1, 0x45, 0x61, 0x4f, 0x99, 0xbc, 0x79, 0xf3,
	0xf0, 0x30, 0x70, 0xb6, 0x20, 0x66, 0xd9, 0x88, 0xe3, 0x19, 0x5a, 0x27, 0x4b, 0x51, 0xed, 0x70,
	0x64, 0xab, 0x0f, 0xad, 0xe1, 0x74, 0x54, 0xbf, 0x4e, 0xe8, 0x7b, 0x45, 0x7e, 0xa9, 0x14, 0x1c,
	0x7f, 0x99, 0x92, 0xba, 0xc9, 0x75, 0xd2, 0x4f, 0x27, 0x61, 0xd6, 0x77, 0x00, 0xbb, 0x8e, 0xe5,
	0x4a, 0x75, 0xa1, 0x55, 0x92, 0xf7, 0x66, 0x1e, 0x4b, 0xf1, 0xaa, 0x6f, 0xa0, 0x33, 0x12, 0x36,
	0x4d, 0xa8, 0x5b, 0x48, 0xb7, 0x95, 0x46, 0xd2, 0xe0, 0x75, 0x67, 0x35, 0x25, 0xb7, 0x2e, 0x72,
	0x52, 0x4f, 0xd0, 0x9e, 0x9a, 0x2a, 0x44, 0xea, 0x0a, 0xa3, 0x3c, 0x1e, 0x9a, 0xf7, 0x2e, 0xfe,
	0xe5, 0x96, 0x2b, 0x7d, 0x34, 0x78, 0xd9, 0x5a, 0x45, 0xd4, 0x23, 0xb4, 0x6a, 0x94, 0xb0, 0x51,
	0x97, 0x07, 0x3f, 0xf6, 0xde, 0xbd, 0xf3, 0xbf, 0x71, 0xe0, 0x0c, 0x9f, 0xa1, 0x5f, 0x08, 0x2e,
	0x8a, 0x19, 0xad, 0xc5, 0x7a, 0xa4, 0x1f, 0x53, 0x5a, 0x26, 0x8f, 0x1b, 0xca, 0x70, 0xee, 0x6c,
	0x8e, 0xfb, 0x2d, 0x0f, 0xd3, 0x37, 0xc9, 0x3f, 0xc7, 0x35, 0x65, 0x9c, 0xbc, 0x77, 0x10, 0xef,
	0x23, 0x31, 0x3b, 0x09, 0xd3, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x7f, 0x6f, 0x7c,
	0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	// Sends a hello greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/protobuf.HelloService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	// Sends a hello greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.HelloService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

// HolaServiceClient is the client API for HolaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HolaServiceClient interface {
	// Sends a hola greeting
	SayHola(ctx context.Context, in *HolaRequest, opts ...grpc.CallOption) (*HolaReply, error)
}

type holaServiceClient struct {
	cc *grpc.ClientConn
}

func NewHolaServiceClient(cc *grpc.ClientConn) HolaServiceClient {
	return &holaServiceClient{cc}
}

func (c *holaServiceClient) SayHola(ctx context.Context, in *HolaRequest, opts ...grpc.CallOption) (*HolaReply, error) {
	out := new(HolaReply)
	err := c.cc.Invoke(ctx, "/protobuf.HolaService/SayHola", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HolaServiceServer is the server API for HolaService service.
type HolaServiceServer interface {
	// Sends a hola greeting
	SayHola(context.Context, *HolaRequest) (*HolaReply, error)
}

// UnimplementedHolaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHolaServiceServer struct {
}

func (*UnimplementedHolaServiceServer) SayHola(ctx context.Context, req *HolaRequest) (*HolaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHola not implemented")
}

func RegisterHolaServiceServer(s *grpc.Server, srv HolaServiceServer) {
	s.RegisterService(&_HolaService_serviceDesc, srv)
}

func _HolaService_SayHola_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HolaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HolaServiceServer).SayHola(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.HolaService/SayHola",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HolaServiceServer).SayHola(ctx, req.(*HolaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HolaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.HolaService",
	HandlerType: (*HolaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHola",
			Handler:    _HolaService_SayHola_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
