# config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: grpc-server
  profiles:
    include:
    - logging
    - locale
    - grpc

logging:
  level: info
#
#jaeger:
#  config:
#    serviceName: ${app.name}
#    sampler:
#      type: const
#      param: 1
#    reporter:
#      logSpans: true
#      localAgentHostPort: jaeger-agent.istio-system:6831
#      bufferFlushInterval: 1000000
