# config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: grpc-client
  profiles:
    active: default
    include:
    - logging
    - locale
    - grpc

logging:
  level: info

